"""Shared helpers for the COD Risk Score demo pipeline.

SYNTHETIC DATA - for illustration only. This is NOT real Shopee data.

The most important idea here is "as of order time": every feature for an order
may only look at events that happened strictly BEFORE that order was placed.
We do this fast with one trick: give every event a sort key

    key = group_id * KEY_GAP + time_in_days

so that all events of one buyer (or one area) sit next to each other, in time
order. Then `np.searchsorted` tells us, for any order, how many of that group's
events happened before it, or inside a window such as the last 90 days.
"""
from pathlib import Path

import numpy as np
import pandas as pd
import yaml

ROOT = Path(__file__).resolve().parent.parent
DATA_DIR = ROOT / "data"
DOCS_DIR = ROOT / "docs"
REPORTS_DIR = ROOT / "reports"

SYNTHETIC_NOTE = (
    "SYNTHETIC DATA - for illustration only. This is NOT real Shopee data. "
    "Generated by the cod_risk_demo pipeline for a case competition demo."
)

# Bigger than the whole simulation (in days) plus any window, so groups never overlap.
KEY_GAP = 10_000.0


def load_config():
    with open(ROOT / "config.yaml", encoding="utf-8") as f:
        return yaml.safe_load(f)


def day_number(date_str, sim_start):
    """Days between sim_start and a date string (can be negative)."""
    return (pd.Timestamp(date_str) - pd.Timestamp(sim_start)).days


def days_to_datetime(days, sim_start):
    """Turn 'days since sim_start' (float) back into real timestamps."""
    return pd.Timestamp(sim_start) + pd.to_timedelta(np.asarray(days), unit="D")


def write_csv(df, path):
    """Write a CSV whose first line is the synthetic-data note (as a # comment)."""
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w", encoding="utf-8", newline="") as f:
        f.write(f"# {SYNTHETIC_NOTE}\n")
        df.to_csv(f, index=False)


def read_csv(path):
    """Read a CSV written by write_csv (skips the # note line)."""
    return pd.read_csv(path, comment="#")


def write_text(path, text):
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


# ---------------------------------------------------------------------------
# As-of-time counting
# ---------------------------------------------------------------------------
def sum_before(ref_group, ref_time, q_group, q_time, values=None, window=None):
    """For each query (group, time), look at reference events of the SAME group
    that happened strictly before the query time (and, if `window` is given,
    no earlier than time - window).

    Returns a dict with "count" and, for every array in `values`, the sum of
    that array over the matching events.
    """
    ref_key = np.asarray(ref_group, dtype=float) * KEY_GAP + np.asarray(ref_time, dtype=float)
    order = np.argsort(ref_key, kind="stable")
    ref_key_sorted = ref_key[order]

    q_group = np.asarray(q_group, dtype=float)
    q_key = q_group * KEY_GAP + np.asarray(q_time, dtype=float)

    # hi = first event at or after the query time -> everything before it is "past"
    hi = np.searchsorted(ref_key_sorted, q_key, side="left")
    if window is None:
        lo = np.searchsorted(ref_key_sorted, q_group * KEY_GAP - KEY_GAP / 2, side="left")
    else:
        lo = np.searchsorted(ref_key_sorted, q_key - window, side="left")

    out = {"count": hi - lo}
    for name, v in (values or {}).items():
        running = np.concatenate([[0.0], np.cumsum(np.asarray(v, dtype=float)[order])])
        out[name] = running[hi] - running[lo]
    return out


def last_time_before(ref_group, ref_time, q_group, q_time):
    """Time of the latest reference event of the same group strictly before the
    query time. NaN if there is none."""
    ref_group = np.asarray(ref_group, dtype=float)
    ref_time = np.asarray(ref_time, dtype=float)
    ref_key = ref_group * KEY_GAP + ref_time
    order = np.argsort(ref_key, kind="stable")
    ref_key_sorted, group_sorted, time_sorted = ref_key[order], ref_group[order], ref_time[order]

    q_group = np.asarray(q_group, dtype=float)
    q_key = q_group * KEY_GAP + np.asarray(q_time, dtype=float)
    idx = np.searchsorted(ref_key_sorted, q_key, side="left") - 1
    safe = np.clip(idx, 0, None)
    found = (idx >= 0) & (len(ref_key_sorted) > 0)
    if len(ref_key_sorted):
        found &= group_sorted[safe] == q_group
        return np.where(found, time_sorted[safe], np.nan)
    return np.full(len(q_key), np.nan)


def order_context(orders, cfg):
    """Order-context features that only need PLACED orders (no outcomes):
    value_vs_aov and freq_change_ratio. Used by the generator (hidden rule uses
    freq_change_ratio) and by build_features, so both use the same definition.

    `orders` needs columns: buyer_id, order_day, order_value.
    """
    fc = cfg["features"]
    b, t, v = orders["buyer_id"].to_numpy(), orders["order_day"].to_numpy(), orders["order_value"].to_numpy()

    # All earlier orders of the same buyer (placed before this one).
    past = sum_before(b, t, b, t, values={"value": v})
    n_prior = past["count"]
    past_aov = np.divide(past["value"], n_prior, out=np.ones_like(t), where=n_prior > 0)
    value_vs_aov = np.where(n_prior > 0, v / past_aov, 1.0)

    # Orders in the last 30 days vs the buyer's (smoothed) usual monthly rate.
    last30 = sum_before(b, t, b, t, window=fc["freq_window_days"])["count"]
    first_day = orders.groupby("buyer_id")["order_day"].transform("min").to_numpy()
    months_seen = (t - first_day) / 30.44
    avg_monthly = (n_prior + fc["freq_prior_monthly_rate"] * fc["freq_prior_months"]) / (
        months_seen + fc["freq_prior_months"]
    )
    freq_change_ratio = last30 / avg_monthly

    return pd.DataFrame(
        {
            "value_vs_aov": np.round(value_vs_aov, 4),
            "freq_change_ratio": np.round(freq_change_ratio, 4),
            "n_prior_placed": n_prior,
        },
        index=orders.index,
    )
